version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/SpringBootsMongo.jar
    - scripts/*.sh
    - appspec.yml
    - customs.json
    - ssl/global-bundle.pem