version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/SpringBootsMongo.jar
    - scripts/server_clear.sh
    - scripts/server_start.sh
    - scripts/server_stop.sh
    - scripts/fix_privileges.sh
    - appspec.yml
  discard-paths: yes